name: summarizer_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow
      - transformers==4.44.2
      - torch==1.13.1+cu116
      - torchvision==0.14.1+cu116
      - torchaudio==0.13.1
      - langchain==0.2.17
      - pandas
      - langchain-huggingface==0.0.3
      - langchain-community==0.2.19
      - --extra-index-url=https://download.pytorch.org/whl/cu116
